change hash_map_t key type for gcc v8
Hello!

I didn't know about relacy before. Will surely use it in the future.

While compiling with `gcc version 8.2.1` on Linux, `GNU libc 2.28`, I've
encountered following errors:

```
/usr/include/c++/8.2.1/bits/stl_map.h: In instantiation of ‘class std::map<const void*, long unsigned int, std::less<const void*>, rl::raw_allocator<std::pair<const void*, long unsigned int> > >’:
../subprojects/base_library/gitmodules/relacy/relacy/context_addr_hash.hpp:55:45:   required from here
/usr/include/c++/8.2.1/bits/stl_map.h:122:21: error: static assertion failed: std::map must have the same value_type as its allocator

```

Tried to fix them by swapping `map<void const*, ...>` keys to `map<void* const, ...>`.

Thanks!